[package]
name = "bft_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bft_test_utils = { path = "../bft_test_utils" }

[dependencies]
num-traits = "0.2.18"
log = "0.4.21"
